version: '3.2'
services:
     server:
        image: nginx
        restart: always
        container_name: ${SERVER_NAME}
        ports:
           - ${HTTP_PORT}:80
           - ${HTTPS_PORT}:443
        volumes:
           - ./logs/access.log:/var/log/nginx/access.log
           - ../:/var/local/
           - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
           - ./nginx/site.conf:/etc/nginx/nginx.conf
        depends_on:
           - php
           - mongo
     php:
        build: .
        restart: always
        container_name: ${APP_NAME}
        volumes:
            - ../:/var/local/
        working_dir: /var/local
     mongo:
        image: mongo
        container_name: ${MONGO_HOST}
        restart: on-failure:3
        ports:
          - ${MONGO_PORT}:27017
        volumes:
          - ${MONGO_DATA}:/data/db
        environment:
           MONGO_INITDB_ROOT_USERNAME: ahmed
           MONGO_INITDB_ROOT_PASSWORD: password
     mongo-express:
        image: mongo-express
        container_name: ${MONGO_ADMIN_PANEL}
        restart: always
        ports:
           - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ahmed
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
#volumes:
#  mongodb:


